### ISSUE TITLE
 Add Quranic Verse of the Day

### ISSUE THREAD

**Issue by AhmedAlRawi0** [AhmedAlRawi0/MyDailyHadith#7]
## Feature: Add Quranic Verse of the Day
**Description**: Implement the backend and frontend logic to fetch and display a daily Quranic verse with translation, explanation, and footnote.

### Subtasks:
- [ ] Add `/daily-verse` endpoint in the backend.
- [ ] Persist Quranic data in `data/data-persistance.json`.
- [ ] Implement logic for toggling between Hadeeth and Quranic data.

**Comment by AhmedAlRawi0** [comment]
We can create another project for this or make it in this repo, where I host the backend on my Render and @mohdels does the frontend on his Vercel

**Comment by AhmedAlRawi0** [comment]
add a card somewhere (next to the header) to direct to it
